name: wdid
description: What did i do?

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.3.0 # 상태관리
  sqflite: ^2.0.0+3 # 로컬 DB
  fl_chart: ^0.36.3 # chart
  cached_network_image: ^3.1.0 # 캐쉬이미지

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true